version: '3'

services :      
    notebook:
      container_name: anaconda_3
      build: jupyter
      labels:
        name: notebook
      ports:
        - "8888:8888"
      volumes:
        - ./../../../app/notebooks:/home/notebooks
      networks:
        vpcbr:
          ipv4_address: 10.6.0.6

networks:
  vpcbr:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.6.0.0/16
#        - gateway: 10.5.0.1
    
    
