version: '3'

services :
    python:
      container_name: workflow
      build: workflow
      ports:
        - "8080:8080"
        - "5000:5000"
        - "6006:6006"
      volumes:
        - ./../../:/home/4aibd-s1-project-ml
      stdin_open: true
      tty: true

networks:
  default:
    driver: bridge

    
    
