version: '3'

services :
    python:
      container_name: python_workflow
      build: python
      ports:
        - "8080:8080"
        - "5000:5000"
        - "6006:6006"
      volumes:
        - ./../../:/home/4aibd-s1-project-ml
      stdin_open: true
      tty: true
      networks:
        workflow:
          ipv4_address: 12.6.0.6

networks:
  workflow:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 12.6.0.0/16
#        - gateway: 10.5.0.1

    
    
