version: '3'

services :
    python:
      container_name: python_37
      build: python
      ports:
        - "8000:8000"
      volumes:
        - ./../../:/home/4aibd-s1-project-ml
      stdin_open: true
      tty: true
      networks:
        vpcbr:

networks:
  vpcbr:
    driver: bridge
    
    
