version: '3'

services : 
    python :
      container_name: python36
      build: python
      volumes: 
        - ./python:/srv/python
        - ./data:/srv/data
      stdin_open: true
      tty: true
      links:
        - notebook
      networks:
        vpcbr:
          ipv4_address: 10.6.0.5
     
    notebook:
      container_name: anaconda_3
      build: jupyter
      labels:
        name: notebook
      ports:
        - "8888:8888"
      volumes:
        - ./../../notebooks:/home/notebooks
        - ./../../data/blood_transfusion:/home/data
      networks:
        vpcbr:
          ipv4_address: 10.6.0.6

networks:
  vpcbr:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.6.0.0/16
#        - gateway: 10.5.0.1
    
    
