version: '3'

services :
    notebook:
      container_name: anaconda_3
      build: jupyter
      labels:
        name: notebook
      ports:
        - "8888:8888"
      volumes:
        - ./../../default/apps/notebooks/:/home/4aibd-s1-project-ml
        - ~/../../Volumes/SAMSUNG/KaggleDataSet/iwildcam-2019-fgvc6/:/home/4aibd-s1-project-ml/iwildcam_2019_fgvc6
      stdin_open: true
      tty: true

networks:
  default:
    driver: bridge

    
    
